### PR TITLE
review routes

### PR DESCRIPTION
**Pull request by techspeterson**
index, create and delete are working

### CODE REVIEW

**Review by jason20194 — APPROVED** [review]
routes approved

**Review by Marcohylo — APPROVED** [review]
routes ok

**Review by Marcohylo — APPROVED** [review]
ok

**Review by ghost — COMMENTED** [review]
Please use async/await or .then lines 62 and 72

**Comment by techspeterson** [comment]
redundant async functions fixed now, only using .then

**Review by ChristopherDalziel — APPROVED** [review]

**Pull request merged**
